services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "${SERVER_PORT:-5000}:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - .env
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     target: ${NODE_ENV:-development}
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - ./frontend/public:/app/public
  #   ports:
  #     - "${REACT_APP_PORT:-3000}:3000"
    #   env_file:
    #     - .env

volumes:
  backend_node_modules: